//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringDB.Model.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeteringDeviceInfo
    {
        public long Id { get; set; }
        public System.DateTime MountedAt { get; set; }
        public Nullable<System.DateTime> DemountedAt { get; set; }
        public long DeviceId { get; set; }
        public long PointId { get; set; }
    
        public virtual MeteringDevice MeteringDevice { get; set; }
        public virtual MeteringPoint MeteringPoint { get; set; }
    }
}
