//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringDB.Model.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeteringDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeteringDevice()
        {
            this.MeteringDeviceInfo = new HashSet<MeteringDeviceInfo>();
        }
    
        public long Id { get; set; }
        public string DeviceType { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeteringDeviceInfo> MeteringDeviceInfo { get; set; }
    }
}
