//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringDB.Model.Sql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonitoringDbModelContainer : DbContext
    {
        public MonitoringDbModelContainer()
            : base("name=MonitoringDbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MeteringDevice> MeteringDevices { get; set; }
        public virtual DbSet<MeteringPoint> MeteringPoints { get; set; }
        public virtual DbSet<MeteringData> MeteringDataHistory { get; set; }
        public virtual DbSet<MeteringDeviceInfo> MeteringDeviceHistory { get; set; }
    }
}
